//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fundtasia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime TimeDonated { get; set; }
        public decimal Amount { get; set; }
        public string EventId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
        public object ReturnDate { get; internal set; }
    }
}
