//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fundtasia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual User User { get; set; }
    }
}
