//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fundtasia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMerchandise
    {
        public string Email { get; set; }
        public string MerchandiseId { get; set; }
        public System.DateTime PurchaseTime { get; set; }
        public string Size { get; set; }
        public decimal Price { get; set; }
        public string Billingname { get; set; }
        public string StreetAddress { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
    
        public virtual Merchandise Merchandise { get; set; }
        public virtual User User { get; set; }
    }
}
