//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fundtasia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEvent
    {
        public string Email { get; set; }
        public string EventId { get; set; }
        public string Like { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
